### ISSUE TITLE
Expand the definition of SBOL-compliant URI

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/SBOL-specification#101]
SBOL compliant URI's generally simplify URI construction, especially when objects are automatically constructed.  However, sometimes I run into URI collisions when trying to write code that automatically constructs objects, especially when integrating multiple SBOL files into one, and especially when dealing with complicated structural hierarchies.  The following rules might possibly help with these difficulties:

- Allow displayIds to include "/" character, in addition to alphanumeric and underscore
- The definition of SBOL-compliant URIs should specify how to indicate instances.  For example, should it be "component1" or "component_1"?  (I would prefer "component/1")
- The definition of SBOL-compliant URIs might also be expanded to indicate where a ComponentDefinition is in a structural hierarchy.  For example, "https://sys-bio.org/my_component_definition/my_subcomponent/1/my_subcomponent_definition/1/1.0.0"

Of course, there may be philosophical or practical objections to these rules that I'm not seeing immediately, so I'm interested in other people's opinions.  But from where I stand as a library-implementer, these might make things easier.

**Comment by cjmyers** [comment]
I'm quite sympathetic to the challenges in maintaining URI uniqueness.  However, I'm not comfortable with the suggestions that you are making that would change how "/" is used.  

If we use it in the displayId, this would only work if we required the displayId.  Otherwise, it will be impossible to know where the URI prefix ends and the displayId begins.  A non-delimiter symbol might be a better solution.

I'm fine with making suggestions on instance numbers, but I would not like to have it after the slash as it would clash with the version, causing again confusion in parsing of URIs.

I have similar concerns about the third suggestion of adding more levels with "/"s.  

My preference would be to actually take a page from how SynBioHub creates URIs and make the use of URIs by other software follow a similar scheme.  As point of reminder, this is the form used by SBH:

<URL>/public/collectionId/displayId/version
<URL>/user/userId/collectionId/displayId/version

**Comment by jakebeal** [comment]
I believe that this is moot as of SBOL 3, which provides a URI format intended to better address these concerns.

**Comment by cjmyers** [comment]
Agreed
