### ISSUE TITLE
Editing cruft under 'identified', s7.4p18

### ISSUE THREAD

**Issue by mikebissell** [SynBioDex/SBOL-specification#126]
In section 7.4, 'identified', there is an extra space at the top of p18:

"version, wasDerivedFroms , name, description, and annotations."

There's also a confusing marginal redbar around line 2. Not sure what that is meant to indicate, since there's no red insertions or red strikethroughs around line 2.

There is red inserted text at line 22 on p18 as well as well as strikethrough red deleted text around at line 28. Since I did not deliberately download a redlined version, I wasn't sure whether it was intentionally left in this published version. Looks like an oversight to be:

http://sbolstandard.org/wp-content/uploads/2018/01/BBF-RFC114-SBOL2.2.0.pdf

**Comment by jamesscottbrown** [comment]
> There's also a confusing marginal redbar around line 2. Not sure what that is meant to indicate, since there's no red insertions or red strikethroughs around line 2.

The problem is that the change affects *only* a hyperlink. In LaTeX it is indicated by ``\twotwozero{\sbol{wasDerivedFroms}}``: the ``\sbol`` command formats a keyword as blue hypertext, whereas ``\twotwozero`` simply changes the text color. 

The change commands (like ``\twotwozero``) could be changed to also change hypertext color (by adding ``\hypersetup{urlcolor=red}`` to the start of their definition, and ``\hypersetup{urlcolor=sbmlblue}`` at the end), but then they would be less visible. The definition of ``\sbol`` could also be changed to add underlining within the change commands, but then the formatting of the changed sections would be more different than the rest of the document.

> Since I did not deliberately download a redlined version, I wasn't sure whether it was intentionally left in this published version. Looks like an oversight to be

AFAIK, the only published version of the spec has changes highlighted. There should be many other changes indicated, not just on p.18.
