### ISSUE TITLE
v2.2.1: Inconsistent formatting on front page

### ISSUE THREAD

**Issue by mikebissell** [SynBioDex/SBOL-specification#187]
In v2.2.1, the front page consists of four blocks of text:
Editors,
Chair,
Steering Committee,
Additional Authors, by Institution,
Non-contributor Authors, by Institution

The top half of the page is aligned in columns, and it's fairly legible. The bottom half is a center-aligned list, and it is not very legible. The center alignment itself is inconsistent with the top, and it obscures the structure of this list. Arguably the center alignment of the names and institutions is chartjunk, since misaligning columnar data distracts from its homogeneous features.

Suggestion 1: reformat Additional Authors and Non-Author Contributors into columns, like the top half of the page.

Suggestion 2: left-justify all columnar text, for easy scanning.

Suggestion 3: following common practice in typesetting and graphic design, impose a global grid layout on all the name/institution pairs on the page. For example, the human names under Editor, Chair, and Steering Committee should all share the same left alignment offset. Same goes for the institution name column.

Please feel free to contact me for specifics.

**Comment by jamesscottbrown** [comment]
I think that I agree with 2 of your 3 suggestions.

> Suggestion 1: reformat Additional Authors and Non-Author Contributors into columns, like the top half of the page.
 
Each category of contributors was formatted as a table until v2.2.1, at which point the number of contributors had increased to the point where this no longer fitted on one page without changing the style. It would probably be better to reduce the size of text or margins so that the tabular structure could be retained.

> Suggestion 2: left-justify all columnar text, for easy scanning

I'm not sure I agree. There are currently two columns: ``name``, and ``institution, country``. ``Name`` should definitely be left aligned.

 However, the case for left-aligning ``institution, country`` is less clear.  In my opinion, it's preferable to right-align this column, since this looks more symmetric and makes int easier to scan the list of countries.

Alternatively, ``Country`` could be split into a third column, but I think that the space this would add between the institution and country would look weird.

> Suggestion 3:   . . impose a global grid layout

Uniform alignment would be achieved if the tables were merged into a single ``table`` environment, and formatted the headings as

     \multicolumn{2}{c}{ \textbf{Editors:} } 


I have another suggestion for this table: I think that some it would be useful to add some kind of brace or vertical line to group contributors from the same institution

**Comment by cjmyers** [comment]
This was a very challenging page to layout and keep on one page.  We really have a lot of authors now, so it is not easy to keep it on one page and still have the old format, even with a reduced font, I’m skeptical.  If someone else has ideas how to arrange this page, I’m happy to see it.

**Comment by jakebeal** [comment]
Is this still relevant?  We seem to have stabilized the format again.

**Comment by cjmyers** [comment]
Think we are stabilized on front page.
