### ISSUE TITLE
Split the specification into smaller documents

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#215]
Specification should be split up into smaller documents (chapters?) to make it easier to digest.  These chapters might include:

1. Core : CD, MD, Seq, Coll.
2. Combinatorial
3. Design-build-test : Prov-O, Impl, Expt, Expt Data, Attachment
4. Serialization

**Comment by bbartley** [comment]
Thinking ahead to clarifying the specification for future generation, it would thinking and communication about the data model if we were to present it as two layers:  a lower level for the XML Document Object Model and a higher level for knowledge representation, which includes classes like ComponentDefinition.  Thus I would suggest a chapter:

0. XML Document Object Model

This chapter would include TopLevel, Identified, and Document (which we should adopt into the data model for explicit clarity).

**Comment by jakebeal** [comment]
@bbartley Since this is about XML, wouldn't this be part of 4. Serialization?  Or are you thinking of something not XML-dependent that's more about the general notion of semantic web objects?

**Comment by bbartley** [comment]
Sure you could put it there.  Just change the title of the chapter to XML Document Object Model and Serialization.  My agenda here is to push us to think about the classes in the core data model that relate to the synthetic biology domain as separate from the classes that concern serialization.  Ideally, it should be possible for a library user to create an SBOL data structure entirely independent of an XML document or even an RDF graph.  Otherwise your knowledge abstraction is being contaminated with what Thomas Gruber calls "encoding bias".

**Comment by cjmyers** [comment]
This is obsolete, since the serialization and other things have changed or been removed already.
