### ISSUE TITLE
Inconsistent use of identifiers.org URLs in SBOL 3.0

### ISSUE THREAD

**Issue by goksel** [SynBioDex/SBOL-specification#366]
Identifiers.org started using https. It also removed the catalog id between identifiers.org and  a term name.
Examples:
SBOL spec example using the recent identifier.org URL scheme.
- https://identifiers.org/SBO:0000251

SBOL spec examples using the recent identifier.org URL scheme.
- http://identifiers.org/biomodels.sbo/SBO:0000169
- http://identifiers.org/so/SO:0000987

**Comment by udp** [comment]
Thanks Goksel.  Looking at the tracker, I think we may have enough of these niggling issues to warrant an SBOL 3.0.1 release before we finalise our initial SBOL3 implementations.

**Comment by tcmitchell** [comment]
All of the SBOL3 example files in SynBioDex/SBOLTestSuite use the new syntax as in https://identifiers.org/SBO:0000290

Some of the comments above use `HTTP` and not `HTTPS` as the protocol in the URI. All of the SBOL3 examples use `HTTPS`, as does the original description on this issue. Note: I have used all caps in this paragraph for emphasis. I think in practice we want these to be lower case as in https://identifiers.org/SBO:0000290

**Comment by goksel** [comment]
Jake, as far as I know what you refer to as "{PREFIX}:{TERM_ID}" is actually "{TERM_ID}" in the OBO ontologies. For example SO:0000167 is actually an ontology term in the Sequence Ontology. Any other ontology can use the same term in theory, although this is unlikely. I assume and hope that ontology developers would avoid using similar terms.

Yes, all identifiers. org URLs should start with "https://identifiers.org/".

**Comment by jakebeal** [comment]
In order to be resolved by identifiers.org, however, the ontology has to register a prefix that is unique with respect to all other ontologies served by identifiers.org. "Compact Identifiers consist of an assigned unique prefix and a local provider designated accession number (prefix:accession)."  

The prefix is curated by identifiers.org, in response to a [prefix registration request](https://registry.identifiers.org/prefixregistrationrequest) and _not_ by the ontology developer. Thus, uniqueness is guaranteed by the resolution service, even if the ontology developer does something internally that would normally create a conflict.

**Comment by goksel** [comment]
Thanks Jake, I am glad the prefix registration system is in place. It seems like this solves the issue and I am happy with the new identifiers.org URLs.
