### ISSUE TITLE
Clarify the use of multiple rdf:type properties

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/SBOL-specification#438]
* Section 5.4 of the draft 3.0.1 specification says, "...an object MUST have no more than one rdfType property in the 'http://sbols.org/v3#' namespace." There is no statement in this section about rdf:type properties outside the SBOL3 namespace. Are SBOL objects allowed to have rdf:type properties outside the SBOL3 namespace? And if so are there any restrictions?
* Section 6.11 of the 3.0 specification (unchanged in the draft 3.0.1 specification) says, "application-specific types MUST have two rdf:type properties: one type outside of the SBOL namespace AND an additional SBOL type of either ... TopLevel ... [or] Identified". The common interpretation of this statement is the extension objects must have _exactly two_ rdf:type properties. This seems overly restrictive and could be loosened to allow multiple rdf:type properties outside the SBOL3 namespace.

**Comment by jakebeal** [comment]
The second bullet is addressed in pull #445

**Comment by jakebeal** [comment]
I can't actually figure out how that information got into the draft that you were looking at. There is no Section 5.4 in the current draft, and I haven't found those words in any of the recent commits. The most recent statement along these lines that I can find was from 2018, when this was introduced into SBOL 2.

I can only conclude that this was an artifact of some sort of bad merge/history behavior, and that the problem does not currently exist, since the current spec draft allows multiple rdf:type values.

**Comment by jakebeal** [comment]
Found it; this was introduced in @cjmyers initial validation rules work, and only exists on that unmerged branch.

**Comment by jakebeal** [comment]
Fix now included in pull #440
