### ISSUE TITLE
Rules for inherited, required, and optional properties should be revised

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#44]
The way these are currently written makes them hard to check.  They should be rewritten of the form that list what fields are required and allowed, and indicate all others are not allowed.  This can now be checked as it would fail when a field that is not listed appears.

**Comment by bbartley** [comment]
I agree the way these are currently written makes them hard to check.  Up until now how have you decided which fields are required and allowed -- is this based on cardinality in the UML?  If required and allowed fields are already defined elsewhere in the spec, then I see no problem with rewriting these validation rules.

**Comment by bbartley** [comment]
This rule will be revised to explicitly state which fields are permitted and which are not.

**Comment by cjmyers** [comment]
Done.

**Comment by jakebeal** [comment]
As written, these currently create a new and serious problem.  By prohibiting properties other than what is written, this means that:

1. Annotations have been prohibited, since these are properties not on the list.
2. Adding new properties to the spec cannot be backward compatible, since the new properties are not backward compatible.

These also create a maintenance nightmare, since adding a property means changing lots of rules.

I suggest that these instead state: 

    A \sbol{[Child]} is REQUIRED to comply with all rules for the \sbol{[Parent]} class.

This takes the focus off of the properties per se, and makes explicit something that has previously been assumed but not stated, that the child class has to obey all of the rules of the parent class.  Those rules then include requirements for properties, which can be readily followed.

**Comment by jakebeal** [comment]
Resolution:

* Annotations are actually in the list, it just wasn't obvious to me because they were listed as the generic clump: "annotations."
* Adding new properties to the spec will not be backward compatible and this has been determined to be desired: we need to support the backward converting in the libraries.

The requirement to comply with validation rules for superclasses is taken as implicit from the UML diagram.
