### ISSUE TITLE
Remove rule 10205

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-specification#45]
I don't think local uniqueness of display ids should be a rule, since using the same display id for a top-level object and a child object can be useful.

**Comment by zgzn** [comment]
But we should require two top-level objects in the same SBOL document to be unique, as we are checking this in URICompliance.keyExistsInAnyMap.

**Comment by cjmyers** [comment]
Their identities must be, but displayIds do not need to be.  This could be if they are not compliant OR simply different versions.

Chris

**Comment by graik** [comment]
I think this is something that you would need to discuss with the "RDF people", e.g. in Newcastle. The URI of an object should be namespace + displayID. In this case, two objects within the same namespace must not have the same displayID because they otherwise would end up with the same URI. The problem of course is that URI = namespace + displayID is a guideline rather than a hard rule in SBOL and nowhere enforced. What happens to this guideline if you introduce versioning is also left unclear, I guess. It looks to me that this is all falling into the scope of a discussion about best practices in URI minting and resolution.
/Raik

**Comment by cjmyers** [comment]
I agree with what you say but there is already a rule that says URIs must be unique. This rule is to strong since a perfectly okay practice is to use a URI for a child object that has the same URI of a top-level. For example,

Authority/GFP
Authority/Gene
   Authority/Gene/GFP
       Where this may be a component instance reference the CD for GFP

Chris

**Comment by graik** [comment]
I think I don't understand the example. You want to give the same URI to the component instance and the CD? That wouldn't be a good idea, would it?

**Comment by cjmyers** [comment]
No they are not the same URI.  They simply share the same displayId.

**Comment by cjmyers** [comment]
Redundant, removed.
