### ISSUE TITLE
Change ComponentReference "hasFeature" to "refersTo"

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#461]
The `hasFeature` property of `ComponentReference` conflicts in type with the `hasFeature` property of `Component`, because in `ComponentReference` this is a pointer while in `Component` it is a child object. This causes difficulty for defining the ontology, because the property has contextual meaning.

We propose that `hasFeature` was never actually a good name for the `ComponentReference` property in the first place, since `ComponentReference`'s other property, `inChildOf` is also a `Feature` (subclass). We thus propose to resolve the type conflict by renaming ComponentReference to `refersTo`, which is a better description of its meaning.

**Comment by jakebeal** [comment]
Assigning this to library maintainers, since we believe this change can be made without an SEP if all of the library maintainers agree.

**Comment by jakebeal** [comment]
@udp and @tcmitchell have indicated assent; @goksel , I assume you're OK with it since you've already got a branch in the ontology incorporating the change. Can you please confirm?

**Comment by tcmitchell** [comment]
A number of files in SBOLTestSuite/SBOL3 will need to be updated to implement this change:
* combine2020
* multicellular
* toggle_switch
* multicellular_simple

@goksel can you update these files on a branch (`feature/sbolcomposition` as in [sbol-owl3](https://github.com/SynBioDex/sbol-owl3)?) so that we can coordinate development of this change?

I found these issues after regenerating the SHACL rules using https://github.com/SynBioDex/sbol-shacl. I pushed a new `feature/sbolcomposition` branch that contains this change in case others want to try out the updated SHACL rules.

**Comment by jakebeal** [comment]
@goksel has affirmed as well, so I am going to set up a pull request for this change in the spec.

**Comment by jakebeal** [comment]
I believe this should have been closed already when #463 was merged.
