### ISSUE TITLE
Refactoring SBOL to have less confusing names

### ISSUE THREAD

**Issue by eda-ricercatore** [SynBioDex/SBOL-specification#468]
For subsequent versions of SBOL, can components and subcomponents be renamed to definitions/specifications and implementations to avoid confusion?

This is because the former refer to templates/definitions/specifications/types, and the latter refer to specific implementations of functions in genetic/protein sequences.

Quotes from the chat session of a recent IWBDA workshop on SBOL.

> From Tom Mitchell to Everyone:  02:18 PM
> @Giovanni that’s probably a good topic for further discussion via an issue at https://github.com/SynBioDex/SBOL-specification
> 
> From Jacob Beal to Everyone:  02:18 PM
> different folks suggesting what terms are best for these things over the years.  Different people seem to have different ideas about what is least confusing…

I am thinking from an engineering, or computer science perspective, where we differentiate specifications/definitions from implementations.

Thank you so much, and have a good day!

**Comment by jakebeal** [comment]
This doesn't seem to have attracted support, and would require a major version change since it would not be backward compatible. As such, we are going to close it for now with respect to the specification.

If an "aliasing" change is desired, it could be implemented via functions added to a library like SBOL-utilities. I would suggest setting up a pull request there if you wish to pursue this further.
