### ISSUE TITLE
Example codes for NCIT roles do not match NCIT website

### ISSUE THREAD

**Issue by hgscott** [SynBioDex/SBOL-specification#485]
I saw that some of the NCIT codes given as examples on page 82 in section 7.9.2 Media, Inducers, and Other Reagents do not match the codes given on the website (https://ncithesaurus.nci.nih.gov/) as of 2022-07-10.

To match the website the following roles would need to be updated:
NCIT:C19442: Media
NCIT:C95501: Strain

Also, there are two entries on NCIT called cell: NCIT:C12508 and NCIT:C48694. My initial reaction would be that NCIT:C12508 is the definition most people would mean in the host context (C12508 is defined as "The smallest units of living structure capable of independent existence, composed of a membrane-enclosed mass of protoplasm and containing a nucleus or nucleoid" whereas NCIT:C48694 is defined as "Any small compartment.").

**Comment by jakebeal** [comment]
Taking a look at these, it looks like this is a case of multiple definitions for the same word.

NCIT has two entries for "media":
- NCIT:C85504 is "growth medium", with synonym "media" - this is the intended sense for culturing organisms. You can get this with tyto as `tyto.NCIT.growth_medium`
- NCIT:C19442 is "media", with the definition of "Any mechanism of mass communication". This is the one tyto will give if you ask for `tyto.NCIT.media`

For "strain", there are five(!) entries:
- NCIT: C14419 is "organism strain", with synonym "strain", which is the intended sense for talking about cell lines. You can get this with tyto as `tyto.NCIT.organism_strain`
- NCIT:C95501 is "A feeling of difficulty that causes worry or emotional tension"
- NCIT:C185651 is "The act of making a very hard effort, possibly at one's limit."
- NCIT:C77530 and NCIT:C96373 identify terms from another ontology, the "CDISC SEND Terminology"

For these two, I believe the right fix is to update the specification to give the proper ontology name rather than the synonym.

With regards to cell: I agree with you that the intended sense should indeed be NCIT:C12508.

**Comment by jakebeal** [comment]
I've put together a proposed fix. I believe that the Cell fix can go in without any significant effect on users, because a) it's just an example of a term that one might use, and doesn't change correctness of documents, and b) it hasn't been used much anyway.
