### ISSUE TITLE
Create an XSD for SBOL2

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-specification#6]
Mike B. ``"the program doing [the deserialization] SHOULD verify that all of the property values encoded therein have the right type...."
Not everybody knows how to apply XML+XSD. Maybe we should give new users a big hint: they can just use any correctly implemented SBOL 2.0 XSD file along with a validating XML parser to do this stuff automatically. We really don't want implementators getting scared off by the burden imposed by this section of the spec. Let's perhaps additionally recommend as a bootstrapping exercise to grab an SBOL 2.0 XSD file out of a recognized reference implementation (libSBOLj, for instance), then start by feeding the XSD and the user's SBOL document in question to a validating XML parser such as xmllint, which is FOSS, works great, and installs in seconds. (Side note: if you choose to give these helpful hints, please make it clear that a given reference implementation is not a spec; if it contains errors, the spec wins.)

A section about completeness and validation that doesn't talk about the available official or unofficial XSDs is incomplete. This part was left out of SBOL 1.1, but now that serialization is a big part of SBOL 2.0, an XSD should be included somehow, if only by reference.'' ANSWER: agreed, we need to do an XSD as soon as possible.  Help would be appreciated. -CJM

I'll get in touch with the libsbol devs and offer to lend a hand. -MB

[imported from LaTeX]

**Comment by mikebissell** [comment]
We should change the name of this to "Create a RELAX NG or XSD schema for SBOL2."

I recently encoded SBOL2-structural into RELAX NG, now testing for internal use. If this goes well, I will release the -structural .rnc schema for review by the community. -functional is next.

Whoever remarked that RELAX NG was the way to go, as opposed to XSD, had it right.

**Comment by jakebeal** [comment]
This is as much library as spec, in some ways. This does not change the spec, though, so it doesn't need any SEP.

**Comment by mikebissell** [comment]
Bump: should definitely change the title of this ticket to **"Create a RELAX NG schema for SBOL2."** 

Nobody seems to believe that it's possible to make an XSD anymore. There appears to be a nondeterministic content model in play, breaking XSD compatibility. RELAX NG, in contrast, is easy.

C. Macklin and I have a partial RELAX NG doc in use for SBOL2-structural. We could conceivably expand it to cover the whole spec.

This is potentially a specification-level artifact because a RELAX NG schema definition is a precise, machine-readable grammar for SBOL2's XML serialization. The specification's hand-typed XML serialization examples are useful, but they are merely human-readable.

**Comment by jakebeal** [comment]
If you build it, I expect that people will embrace it!

**Comment by jakebeal** [comment]
I believe this is now moot, as SBOL 3 simply embraces RDF as its serialization format.

**Comment by cjmyers** [comment]
Agreed.
